### ISSUE TITLE
godot4.2.2.  It looks wrong.

### ISSUE THREAD

**Issue by baiduwen3** [Trixelized/godotHypercasualShader#2]
![image](https://github.com/user-attachments/assets/494ff85f-ba72-400e-9fa1-82233cbf28e7)

**Comment by Trixelized** [comment]
Are you using Compatibility mode? If so, I pushed a fix that should solve this. If not, I am unable to replicate this.

**Comment by baiduwen3** [comment]
> Are you using Compatibility mode? If so, I pushed a fix that should solve this. If not, I am unable to replicate this.

After opening the project, it defaults to mobile mode, which is a display issue. And Forward+and compatibility modes are also the same issue. Both of my computers have this error when turned on. Both. tscn files open like this.

**Comment by Trixelized** [comment]
Added a new branch, does it still happen using this one https://github.com/Trixelized/godotHypercasualShader/tree/normalfix ?

**Comment by baiduwen3** [comment]
> Added a new branch, does it still happen using this one https://github.com/Trixelized/godotHypercasualShader/tree/normalfix ?

Yeah! It's working properly now！
